name: Multi Module Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-ru1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build RU1
        run: mvn -B clean install -pl ru1 -am

      - name: Upload RU1 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ru1
          path: ru1/target/*.jar


  build-ru2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build RU2
        run: mvn -B clean install -pl ru2 -am

      - name: Upload RU2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ru2
          path: ru2/target/*.jar


  build-ru3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build RU3
        run: mvn -B clean install -pl ru3 -am

      - name: Upload RU3 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ru3
          path: ru3/target/*.jar


  assembly:
    needs: [build-ru1, build-ru2, build-ru3]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Assembly
        run: mvn -B clean install -pl assembly -am


  installer:
    needs: assembly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Installer
        run: mvn -B clean install -pl installer -am

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: installer/target/*.jar
